return {
    Ralts = true,
    Swablu = true,
    Bagon = true,
    Turtwig = true,
    Chimchar = true,
    Piplup = true,
	Dedenne = true,
    Carbink = true,
    Goomy = true,
    Turtonator = true,
    Skwovet = true,
    Galarian_Meowth = true,
    Hisuian_Zorua = true,
    Terapagos = true,
    customJokers = true,
    customStakes = true,
    familyStickers = false,
    -- customItems = true,
}